export const GAME_ENGINE_ADDRESS = process.env.GAME_ENGINE_ADDRESS || '127.0.0.1:10000';


export const GAME_ENGINE_BET_RETRY_COUNT = +process.env.GAME_ENGINE_BET_RETRY_COUNT || 10;
export const GAME_ENGINE_BET_RETRY_MIN_TIMEOUT = +process.env.GAME_ENGINE_BET_RETRY_MIN_TIMEOUT || 500;
export const GAME_ENGINE_BET_RETRY_MAX_TIMEOUT = +process.env.GAME_ENGINE_BET_RETRY_MAX_TIMEOUT || 1000;
export const GAME_ENGINE_BET_MAX_RETRY_TIME = +process.env.GAME_ENGINE_BET_MAX_RETRY_TIME || 10000;
